#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""conversationalist - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Openai (LLM)
- Elevenlabs (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import os

import aiohttp
from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.frames.frames import LLMRunFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.runner import PipelineRunner
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.runner.types import RunnerArguments, SmallWebRTCRunnerArguments
from pipecat.services.deepgram.stt import DeepgramSTTService
from pipecat.services.elevenlabs.tts import ElevenLabsTTSService
from pipecat.services.openai.tts import OpenAITTSService
# from pipecat.services.heygen.video import NewSessionRequest
# from pipecat.services.heygen.video import HeyGenVideoService, HeyGenVideoSettings
# from pipecat.services.heygen.client import ServiceType
# from pipecat.services.heygen.api_liveavatar import LiveAvatarNewSessionRequest
from pipecat.services.openai.llm import OpenAILLMService
# from pipecat.transports.services.helpers import WebRTC
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport
# from pipecat.transports.smallwebrtc import SmallWebRTCTransport
from pipecat_tail.observer import TailObserver
from pipecat_whisker import WhiskerObserver
from pipecat.processors.frameworks.rtvi import RTVIProcessor

load_dotenv(override=True)


async def run_bot(transport: BaseTransport):
    """Main bot logic."""
    logger.info("Starting bot")
    
    # 1. REMOVED the redundant SmallWebRTCTransport initialization here.
    # It is already passed in as an argument!

    rtvi = RTVIProcessor(transport=transport)

    async with aiohttp.ClientSession() as session:
        # Speech-to-Text service
        stt = DeepgramSTTService(api_key=os.getenv("DEEPGRAM_API_KEY"))

    
        # Text-to-Speech service    
        tts = OpenAITTSService(
            api_key=os.getenv("OPENAI_API_KEY"),
            voice="shimmer",
            model= 'tts-1-hd'
            )

        # LLM service
        llm = OpenAILLMService(
            api_key=os.getenv("OPENAI_API_KEY"),
            model= "gpt-5.5", # Pass directly
            system_instruction="""You are a friendly, conversational AI, named Sam. Speak in short, natural sentences. Use contractions (like 'don't' instead of 'do not'). Occasionally use conversational fillers like 'well' or 'actually' to sound more human. 
            Never use bullet points or lists.
            """,
        )

        context = LLMContext()
        user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
            context,
            user_params=LLMUserAggregatorParams(
                vad_analyzer=SileroVADAnalyzer(),
            ),
        )

        # Pipeline
        pipeline = Pipeline(
            [
                transport.input(),
                rtvi,
                stt,
                user_aggregator,
                llm,
                tts,
                transport.output(),
                assistant_aggregator,
            ]
        )

        task = PipelineTask(
            pipeline,
            params=PipelineParams(
                enable_metrics=True,
                audio_out_sample_rate=24000,
                audio_in_sample_rate=16000,
                allow_interruptions=True,
                interruption_filter_type = 'none',
                enable_rtvi=True
            ),
            rtvi_processor=rtvi,
            observers=[
                WhiskerObserver(pipeline),
                TailObserver(),
            ],
        )

        @task.rtvi.event_handler("on_client_ready")
        async def on_client_ready(rtvi):
            await rtvi.set_bot_ready() # Important: Tell the UI we are ready
            context.add_message({"role": "user", "content": "Please introduce yourself."})
            await task.queue_frames([LLMRunFrame()])

        runner = PipelineRunner(handle_sigint=False)
        await runner.run(task)


async def bot(runner_args):
    """Main bot entry point."""

    transport = None

    match runner_args:
        case SmallWebRTCRunnerArguments():
            webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

            transport = SmallWebRTCTransport(
                webrtc_connection=webrtc_connection,
                params=TransportParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                    camera_out_enabled=False,
                    video_out_enabled=False,
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    await run_bot(transport)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
